package:
    name: pyflann
    version: "1.8.5dev"

source:
    git_url: https://github.com/mariusmuja/flann.git
    git_tag: b8a442fd98f8ce32ae3465bfd3427b5cbc36f6a5

build:
    number: 2
    string: py{{CONDA_PY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
    build:
        - python {{PY_VER}}*
        - setuptools
        - flann 1.8.5dev
        - cmake
    run:
        - python {{PY_VER}}*
        - flann 1.8.5dev
        - numpy

test:
    imports:
        - pyflann

about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD
    license_file: COPYING
