package:
    name: megaman
    version: 0.1.1

source:
    git_url: https://github.com/mmp2/megaman.git
    git_tag: v0.1.1

build:
    number: 2
    string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}

requirements:
    build:
        - python >=2.7,<3|>=3.4,{{PY_VER}}*
        - numpy {{NPY_VER}}*
        - cython
        - flann
        - gcc 4.8* # [osx]
    run:
        - python {{PY_VER}}*
        - numpy {{NPY_VER}}*
        - scipy >=0.16
        - scikit-learn >=0.17
        - pyamg
        - pyflann
        - libgcc 4.8* # [osx]

test:
    requires:
        - nose
    imports:
        - megaman
        - megaman.geometry
        - megaman.embedding
        - megaman.utils

about:
    home: http://mmp2.github.io/megaman
    license: BSD
    license_file: LICENSE
