package:
    name: flann
    version: "1.8.5dev"

source:
    git_url: https://github.com/mariusmuja/flann.git
    git_tag: b8a442fd98f8ce32ae3465bfd3427b5cbc36f6a5

build:
    number: 1

requirements:
    build:
        - gcc [osx]
        - hdf5
        - cmake
    run:
        - libgcc [osx]
        - hdf5

about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD
    license_file: COPYING
